# Generated by Django 4.1.5 on 2023-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("make", models.CharField(max_length=100)),
                ("car_model", models.CharField(max_length=100)),
                ("trim", models.CharField(max_length=100)),
                ("dealer_name", models.CharField(max_length=100)),
                ("dealer_street", models.CharField(max_length=100)),
                ("dealer_city", models.CharField(max_length=100)),
                ("dealer_state", models.CharField(max_length=100)),
                ("dealer_zip", models.CharField(max_length=100)),
                ("listing_price", models.FloatField()),
                ("listing_mileage", models.FloatField()),
                ("used", models.BooleanField()),
                ("certified", models.BooleanField()),
                ("style", models.CharField(max_length=100)),
                ("driver_wheels", models.CharField(max_length=100)),
                ("engine", models.CharField(max_length=100)),
                ("fuel_type", models.CharField(max_length=100)),
                ("exterior_color", models.CharField(max_length=100)),
                ("interior_color", models.CharField(max_length=100)),
                ("seller_website", models.URLField()),
                ("first_seen_date", models.DateField()),
                ("last_seen_date", models.DateField()),
                ("dealer_vdp_last_seen_date", models.DateField()),
                ("listing_status", models.CharField(max_length=100)),
            ],
        ),
    ]
