# Generated by Django 4.1.5 on 2023-01-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avg_price_calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="certified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="dealer_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="dealer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="dealer_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="dealer_street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="dealer_vdp_last_seen_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="dealer_zip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="driver_wheels",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="exterior_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="first_seen_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="interior_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="last_seen_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="listing_mileage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="listing_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="listing_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="make",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="seller_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="style",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="trim",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="used",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
