# Generated by Django 4.1.5 on 2023-01-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "avg_price_calculator",
            "0002_alter_car_car_model_alter_car_certified_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="car_model",
            new_name="model",
        ),
    ]
