# Generated by Django 4.1.5 on 2023-01-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avg_price_calculator", "0003_rename_car_model_car_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="driver_wheels",
            new_name="driven_wheels",
        ),
    ]
