# Generated by Django 4.1.5 on 2023-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avg_price_calculator", "0004_rename_driver_wheels_car_driven_wheels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="listing_mileage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="listing_price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="used",
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
    ]
