# Generated by Django 4.1.5 on 2023-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "avg_price_calculator",
            "0006_alter_car_certified_alter_car_listing_mileage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="listing_mileage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="listing_price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
