# Generated by Django 4.1.5 on 2023-01-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "avg_price_calculator",
            "0007_alter_car_listing_mileage_alter_car_listing_price",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="dealer_vdp_last_seen_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="first_seen_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="last_seen_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
