# Generated by Django 4.1.5 on 2023-01-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avg_price_calculator", "0008_alter_car_dealer_vdp_last_seen_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="dealer_vdp_last_seen_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="first_seen_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="last_seen_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
