# Generated by Django 4.1.5 on 2023-01-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "avg_price_calculator",
            "0010_alter_car_listing_mileage_alter_car_listing_price",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="certified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="used",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
