# Generated by Django 4.1.5 on 2023-01-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avg_price_calculator", "0011_alter_car_certified_alter_car_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="listing_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
